# Generated by Django 4.0.6 on 2022-08-11 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('age', models.DecimalField(decimal_places=0, max_digits=12, null=True)),
                ('race', models.CharField(max_length=100, null=True)),
                ('appearance', models.TextField(max_length=500, null=True)),
                ('short_hisotry', models.TextField(max_length=500, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
