# Generated by Django 4.0.6 on 2022-07-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='char',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.DateTimeField(auto_now_add=True)),
                ('race', models.CharField(max_length=200)),
                ('appearance', models.CharField(max_length=366)),
                ('short_hisotry', models.CharField(max_length=300)),
            ],
        ),
    ]
