# Generated by Django 4.0.6 on 2022-07-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='age',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='char',
            name='appearance',
            field=models.TextField(max_length=366),
        ),
        migrations.AlterField(
            model_name='char',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='char',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='char',
            name='race',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='char',
            name='short_hisotry',
            field=models.TextField(max_length=300),
        ),
    ]
