# Generated by Django 4.0.6 on 2022-08-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='user',
            new_name='author',
        ),
    ]
