# Generated by Django 4.0.6 on 2022-07-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_char_age_alter_char_appearance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='char',
            name='appearance',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='char',
            name='short_hisotry',
            field=models.TextField(max_length=500),
        ),
    ]
