# Generated by Django 4.0.6 on 2022-08-11 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_chararacter_limit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chararacter',
            new_name='Characters',
        ),
    ]
