# Generated by Django 4.0.6 on 2022-08-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_character_delete_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField()),
                ('yescomplete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.character')),
            ],
        ),
    ]
