# Generated by Django 4.0.6 on 2022-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='complete',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Complete',
        ),
    ]
